[phases.setup]
nodejs_version = "22.20.0"
npm_version = "10.9.0"

[phases.install]
commands = [
    "npm install --prefix backend",
    "npm install --prefix frontend"
]

[phases.build]
commands = [
    "npm run build --prefix frontend"
]

[phases.start]
commands = [
    "npm run start --prefix backend"
]

[cache]
paths = [
    "backend/node_modules",
    "frontend/node_modules"
]
